"""Add furniture_positions table for drag-and-drop feature

Revision ID: ffd0ace4b641
Revises: 59dead81d14f
Create Date: 2025-11-22 10:14:48.229787

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffd0ace4b641"
down_revision: Union[str, Sequence[str], None] = "59dead81d14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "furniture_positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("x", sa.Float(), nullable=False),
        sa.Column("y", sa.Float(), nullable=False),
        sa.Column("width", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("is_ai_placed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_furniture_position_product", "furniture_positions", ["product_id"], unique=False)
    op.create_index("idx_furniture_position_session", "furniture_positions", ["session_id"], unique=False)
    op.create_index(op.f("ix_furniture_positions_id"), "furniture_positions", ["id"], unique=False)
    op.create_index(op.f("ix_furniture_positions_product_id"), "furniture_positions", ["product_id"], unique=False)
    op.create_index(op.f("ix_furniture_positions_session_id"), "furniture_positions", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_furniture_positions_session_id"), table_name="furniture_positions")
    op.drop_index(op.f("ix_furniture_positions_product_id"), table_name="furniture_positions")
    op.drop_index(op.f("ix_furniture_positions_id"), table_name="furniture_positions")
    op.drop_index("idx_furniture_position_session", table_name="furniture_positions")
    op.drop_index("idx_furniture_position_product", table_name="furniture_positions")
    op.drop_table("furniture_positions")
    # ### end Alembic commands ###
