"""Make price nullable for enquiry based pricing

Revision ID: 185600cfb697
Revises: f0607fc0c831
Create Date: 2025-11-23 13:32:42.073270

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "185600cfb697"
down_revision: Union[str, Sequence[str], None] = "f0607fc0c831"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "price", existing_type=sa.Float(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("products", "price", existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###
