"""add_style_labels_to_curated_looks

Revision ID: c8cc8852497c
Revises: 8a68e41853ba
Create Date: 2025-12-28 17:22:48.694088

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c8cc8852497c"
down_revision: Union[str, Sequence[str], None] = "8a68e41853ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("curated_looks", sa.Column("style_labels", sa.JSON(), nullable=True))
    op.alter_column(
        "products",
        "embedding",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="JSON array of 768 floats for semantic search",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "embedding_text",
        existing_type=sa.TEXT(),
        comment=None,
        existing_comment="Text that was embedded",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "embedding_updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="When embedding was last generated",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "primary_style",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Primary design style (e.g., modern, minimalist)",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "secondary_style",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Secondary design style",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "style_confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment=None,
        existing_comment="Confidence score 0-1 for style classification",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "style_extraction_method",
        existing_type=sa.VARCHAR(length=50),
        comment=None,
        existing_comment="Method used: gemini_vision, text_nlp, manual",
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_product_primary_style"), table_name="products")
    op.create_index(op.f("ix_products_primary_style"), "products", ["primary_style"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_primary_style"), table_name="products")
    op.create_index(op.f("idx_product_primary_style"), "products", ["primary_style"], unique=False)
    op.alter_column(
        "products",
        "style_extraction_method",
        existing_type=sa.VARCHAR(length=50),
        comment="Method used: gemini_vision, text_nlp, manual",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "style_confidence",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        comment="Confidence score 0-1 for style classification",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "secondary_style",
        existing_type=sa.VARCHAR(length=50),
        comment="Secondary design style",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "primary_style",
        existing_type=sa.VARCHAR(length=50),
        comment="Primary design style (e.g., modern, minimalist)",
        existing_nullable=True,
    )
    op.alter_column(
        "products",
        "embedding_updated_at",
        existing_type=postgresql.TIMESTAMP(),
        comment="When embedding was last generated",
        existing_nullable=True,
    )
    op.alter_column(
        "products", "embedding_text", existing_type=sa.TEXT(), comment="Text that was embedded", existing_nullable=True
    )
    op.alter_column(
        "products",
        "embedding",
        existing_type=sa.TEXT(),
        comment="JSON array of 768 floats for semantic search",
        existing_nullable=True,
    )
    op.drop_column("curated_looks", "style_labels")
    # ### end Alembic commands ###
