"""Add chat_logs table for persistent conversation logging

Revision ID: d249967ad91f
Revises: 3b9f95eeafad
Create Date: 2025-12-12 17:21:25.351914

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d249967ad91f"
down_revision: Union[str, Sequence[str], None] = "3b9f95eeafad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("server_type", sa.String(length=10), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("assistant_response", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_chat_logs_session_created", "chat_logs", ["session_id", "created_at"], unique=False)
    op.create_index("idx_chat_logs_user_created", "chat_logs", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_chat_logs_created_at"), "chat_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_chat_logs_id"), "chat_logs", ["id"], unique=False)
    op.create_index(op.f("ix_chat_logs_session_id"), "chat_logs", ["session_id"], unique=False)
    op.create_index(op.f("ix_chat_logs_user_id"), "chat_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_logs_user_id"), table_name="chat_logs")
    op.drop_index(op.f("ix_chat_logs_session_id"), table_name="chat_logs")
    op.drop_index(op.f("ix_chat_logs_id"), table_name="chat_logs")
    op.drop_index(op.f("ix_chat_logs_created_at"), table_name="chat_logs")
    op.drop_index("idx_chat_logs_user_created", table_name="chat_logs")
    op.drop_index("idx_chat_logs_session_created", table_name="chat_logs")
    op.drop_table("chat_logs")
    # ### end Alembic commands ###
