"""Initial schema with all tables

Revision ID: 17429ea8cb77
Revises:
Create Date: 2025-10-07 19:50:55.901670

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17429ea8cb77"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=False)
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=True)
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_sessions_user_id"), "chat_sessions", ["user_id"], unique=False)
    op.create_table(
        "product_search_view",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=500), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("category_name", sa.String(length=100), nullable=True),
        sa.Column("category_path", sa.String(length=500), nullable=True),
        sa.Column("source_website", sa.String(length=50), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("primary_image_url", sa.Text(), nullable=True),
        sa.Column("search_vector", sa.Text(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_search_view_brand"), "product_search_view", ["brand"], unique=False)
    op.create_index(op.f("ix_product_search_view_category_name"), "product_search_view", ["category_name"], unique=False)
    op.create_index(op.f("ix_product_search_view_is_available"), "product_search_view", ["is_available"], unique=False)
    op.create_index(op.f("ix_product_search_view_last_updated"), "product_search_view", ["last_updated"], unique=False)
    op.create_index(op.f("ix_product_search_view_name"), "product_search_view", ["name"], unique=False)
    op.create_index(op.f("ix_product_search_view_price"), "product_search_view", ["price"], unique=False)
    op.create_index(op.f("ix_product_search_view_product_id"), "product_search_view", ["product_id"], unique=False)
    op.create_index(op.f("ix_product_search_view_source_website"), "product_search_view", ["source_website"], unique=False)
    op.create_table(
        "scraping_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("website", sa.String(length=50), nullable=False),
        sa.Column("spider_name", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("status", sa.Enum("SUCCESS", "FAILED", "PARTIAL", "IN_PROGRESS", name="scrapingstatus"), nullable=False),
        sa.Column("products_found", sa.Integer(), nullable=True),
        sa.Column("products_processed", sa.Integer(), nullable=True),
        sa.Column("products_saved", sa.Integer(), nullable=True),
        sa.Column("images_downloaded", sa.Integer(), nullable=True),
        sa.Column("errors_count", sa.Integer(), nullable=True),
        sa.Column("error_messages", sa.JSON(), nullable=True),
        sa.Column("pages_scraped", sa.Integer(), nullable=True),
        sa.Column("requests_made", sa.Integer(), nullable=True),
        sa.Column("average_response_time", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scraping_logs_created_at"), "scraping_logs", ["created_at"], unique=False)
    op.create_index(op.f("ix_scraping_logs_id"), "scraping_logs", ["id"], unique=False)
    op.create_index(op.f("ix_scraping_logs_status"), "scraping_logs", ["status"], unique=False)
    op.create_index(op.f("ix_scraping_logs_website"), "scraping_logs", ["website"], unique=False)
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("analysis_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_session_id"), "chat_messages", ["session_id"], unique=False)
    op.create_index(op.f("ix_chat_messages_timestamp"), "chat_messages", ["timestamp"], unique=False)
    op.create_index(op.f("ix_chat_messages_type"), "chat_messages", ["type"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=True),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("source_website", sa.String(length=50), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column("is_on_sale", sa.Boolean(), nullable=True),
        sa.Column("stock_status", sa.String(length=20), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_product_brand_category", "products", ["brand", "category_id"], unique=False)
    op.create_index("idx_product_price_category", "products", ["price", "category_id"], unique=False)
    op.create_index("idx_product_source_external", "products", ["source_website", "external_id"], unique=False)
    op.create_index(op.f("ix_products_brand"), "products", ["brand"], unique=False)
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(op.f("ix_products_external_id"), "products", ["external_id"], unique=False)
    op.create_index(op.f("ix_products_id"), "products", ["id"], unique=False)
    op.create_index(op.f("ix_products_is_available"), "products", ["is_available"], unique=False)
    op.create_index(op.f("ix_products_is_on_sale"), "products", ["is_on_sale"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_price"), "products", ["price"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=False)
    op.create_index(op.f("ix_products_source_website"), "products", ["source_website"], unique=False)
    op.create_table(
        "product_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("attribute_name", sa.String(length=100), nullable=False),
        sa.Column("attribute_value", sa.Text(), nullable=False),
        sa.Column("attribute_type", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_attribute_name_value", "product_attributes", ["attribute_name", "attribute_value"], unique=False)
    op.create_index(op.f("ix_product_attributes_attribute_name"), "product_attributes", ["attribute_name"], unique=False)
    op.create_index(op.f("ix_product_attributes_id"), "product_attributes", ["id"], unique=False)
    op.create_index(op.f("ix_product_attributes_product_id"), "product_attributes", ["product_id"], unique=False)
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("medium_url", sa.Text(), nullable=True),
        sa.Column("large_url", sa.Text(), nullable=True),
        sa.Column("alt_text", sa.String(length=500), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("file_format", sa.String(length=10), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_product_images_display_order"), "product_images", ["display_order"], unique=False)
    op.create_index(op.f("ix_product_images_id"), "product_images", ["id"], unique=False)
    op.create_index(op.f("ix_product_images_is_primary"), "product_images", ["is_primary"], unique=False)
    op.create_index(op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_is_primary"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_display_order"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index(op.f("ix_product_attributes_product_id"), table_name="product_attributes")
    op.drop_index(op.f("ix_product_attributes_id"), table_name="product_attributes")
    op.drop_index(op.f("ix_product_attributes_attribute_name"), table_name="product_attributes")
    op.drop_index("idx_attribute_name_value", table_name="product_attributes")
    op.drop_table("product_attributes")
    op.drop_index(op.f("ix_products_source_website"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_price"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_is_on_sale"), table_name="products")
    op.drop_index(op.f("ix_products_is_available"), table_name="products")
    op.drop_index(op.f("ix_products_id"), table_name="products")
    op.drop_index(op.f("ix_products_external_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand"), table_name="products")
    op.drop_index("idx_product_source_external", table_name="products")
    op.drop_index("idx_product_price_category", table_name="products")
    op.drop_index("idx_product_brand_category", table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_chat_messages_type"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_timestamp"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_session_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    op.drop_index(op.f("ix_scraping_logs_website"), table_name="scraping_logs")
    op.drop_index(op.f("ix_scraping_logs_status"), table_name="scraping_logs")
    op.drop_index(op.f("ix_scraping_logs_id"), table_name="scraping_logs")
    op.drop_index(op.f("ix_scraping_logs_created_at"), table_name="scraping_logs")
    op.drop_table("scraping_logs")
    op.drop_index(op.f("ix_product_search_view_source_website"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_product_id"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_price"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_name"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_last_updated"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_is_available"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_category_name"), table_name="product_search_view")
    op.drop_index(op.f("ix_product_search_view_brand"), table_name="product_search_view")
    op.drop_table("product_search_view")
    op.drop_index(op.f("ix_chat_sessions_user_id"), table_name="chat_sessions")
    op.drop_table("chat_sessions")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
