"""Add user_preferences table for AI stylist

Revision ID: 61749b6b1dfa
Revises: 9a0d2954ab5d
Create Date: 2025-12-13 17:14:58.532134

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61749b6b1dfa"
down_revision: Union[str, Sequence[str], None] = "9a0d2954ab5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_preferences",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=50), nullable=True),
        sa.Column("preference_mode", sa.String(length=50), nullable=True),
        sa.Column("target_category", sa.String(length=100), nullable=True),
        sa.Column("room_type", sa.String(length=100), nullable=True),
        sa.Column("usage", sa.JSON(), nullable=True),
        sa.Column("overall_style", sa.String(length=100), nullable=True),
        sa.Column("budget_total", sa.Float(), nullable=True),
        sa.Column("room_analysis_suggestions", sa.JSON(), nullable=True),
        sa.Column("category_preferences", sa.JSON(), nullable=True),
        sa.Column("preferences_confirmed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_preferences_id"), "user_preferences", ["id"], unique=False)
    op.create_index(op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_index(op.f("ix_user_preferences_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    # ### end Alembic commands ###
