"""Add chat_session_id to projects table

Revision ID: 3b9f95eeafad
Revises: 5621174fa00b
Create Date: 2025-12-06 11:52:26.867534

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b9f95eeafad"
down_revision: Union[str, Sequence[str], None] = "5621174fa00b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("chat_session_id", sa.String(length=36), nullable=True))
    op.create_index(op.f("ix_projects_chat_session_id"), "projects", ["chat_session_id"], unique=False)
    op.create_foreign_key(None, "projects", "chat_sessions", ["chat_session_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "projects", type_="foreignkey")
    op.drop_index(op.f("ix_projects_chat_session_id"), table_name="projects")
    op.drop_column("projects", "chat_session_id")
    # ### end Alembic commands ###
