"""add_budget_tier_to_homestyling_sessions

Revision ID: 30c8f8403d7c
Revises: a75e7a12d020
Create Date: 2026-01-05 13:20:32.184838

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30c8f8403d7c"
down_revision: Union[str, Sequence[str], None] = "a75e7a12d020"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "homestyling_sessions",
        sa.Column(
            "budget_tier", sa.Enum("essential", "value", "mid", "premium", "ultra_luxury", name="budgettier"), nullable=True
        ),
    )
    op.create_index(op.f("ix_homestyling_sessions_budget_tier"), "homestyling_sessions", ["budget_tier"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_homestyling_sessions_budget_tier"), table_name="homestyling_sessions")
    op.drop_column("homestyling_sessions", "budget_tier")
    # ### end Alembic commands ###
