"""add_api_usage_table

Revision ID: fb1cd2a025d2
Revises: c9d5e6f7a8b0
Create Date: 2026-01-09 20:20:11.915545

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fb1cd2a025d2"
down_revision: Union[str, Sequence[str], None] = "c9d5e6f7a8b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("session_id", sa.String(length=36), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("operation", sa.String(length=50), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("request_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_api_usage_timestamp_provider", "api_usage", ["timestamp", "provider"], unique=False)
    op.create_index("idx_api_usage_user_operation", "api_usage", ["user_id", "operation"], unique=False)
    op.create_index(op.f("ix_api_usage_id"), "api_usage", ["id"], unique=False)
    op.create_index(op.f("ix_api_usage_model"), "api_usage", ["model"], unique=False)
    op.create_index(op.f("ix_api_usage_operation"), "api_usage", ["operation"], unique=False)
    op.create_index(op.f("ix_api_usage_provider"), "api_usage", ["provider"], unique=False)
    op.create_index(op.f("ix_api_usage_session_id"), "api_usage", ["session_id"], unique=False)
    op.create_index(op.f("ix_api_usage_timestamp"), "api_usage", ["timestamp"], unique=False)
    op.create_index(op.f("ix_api_usage_user_id"), "api_usage", ["user_id"], unique=False)
    op.alter_column(
        "curated_looks",
        "room_analysis",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.add_column("homestyling_sessions", sa.Column("budget_tier", sa.String(length=20), nullable=True))
    op.create_index(op.f("ix_homestyling_sessions_budget_tier"), "homestyling_sessions", ["budget_tier"], unique=False)
    op.alter_column(
        "projects",
        "room_analysis",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.create_index(op.f("ix_stores_id"), "stores", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stores_id"), table_name="stores")
    op.alter_column(
        "projects",
        "room_analysis",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_homestyling_sessions_budget_tier"), table_name="homestyling_sessions")
    op.drop_column("homestyling_sessions", "budget_tier")
    op.alter_column(
        "curated_looks",
        "room_analysis",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_api_usage_user_id"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_timestamp"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_session_id"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_provider"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_operation"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_model"), table_name="api_usage")
    op.drop_index(op.f("ix_api_usage_id"), table_name="api_usage")
    op.drop_index("idx_api_usage_user_operation", table_name="api_usage")
    op.drop_index("idx_api_usage_timestamp_provider", table_name="api_usage")
    op.drop_table("api_usage")
    # ### end Alembic commands ###
