version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: omnishop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  omnishop-scraper:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/omnishop
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: tail -f /dev/null  # Keep container running for manual commands

  scheduler:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/omnishop
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python scripts/scheduler.py
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: